# backend/ocr/migrations/0004_alter_receipt_state.py
# Generated by Django 5.2.5 on 2025-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_update_collected_to_ingested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='state',
            field=models.CharField(choices=[('ingested', 'Ingested'), ('ocr_done', 'OCR done'), ('vectorized', 'Vectorized'), ('brand_store_identified', 'Brand/Store identified')], db_index=True, default='ingested', max_length=32),
        ),
    ]
