# Generated by Django 5.2.5 on 2025-08-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_alter_receipt_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='gmail_attachment_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='gmail_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='received_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='receipt',
            name='source',
            field=models.CharField(db_index=True, default='gmail', max_length=32),
        ),
        migrations.AddField(
            model_name='receipt',
            name='subject',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['source'], name='ix_receipt_source'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['gmail_message_id'], name='ix_receipt_gmail_msg'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('gmail_attachment_id__isnull', False)), fields=('source', 'gmail_attachment_id'), name='uq_receipt_src_attach'),
        ),
    ]
