# Generated by Django 5.2.5 on 2025-08-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_receipt_gmail_attachment_id_receipt_gmail_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='gmail_attachment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='gmail_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
