# Generated by Django 5.2.5 on 2025-08-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_alter_receipt_gmail_attachment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='gmail_attachment_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
