# Generated by Django 5.2.5 on 2025-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job', models.CharField(db_index=True, max_length=64)),
                ('initiated_by', models.CharField(default='cli', max_length=32)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'running'), ('ok', 'ok'), ('failed', 'failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'status', 'started_at'], name='ops_jobrun_job_58dfa4_idx')],
            },
        ),
    ]
