# Generated by Django 5.2.5 on 2025-08-12 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0001_create_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=16)),
                ('triggered_by', models.CharField(blank=True, max_length=64)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('log_path', models.CharField(blank=True, max_length=512)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_runs',
                'indexes': [models.Index(fields=['job_name', 'status', 'started_at'], name='ix_jobruns_main')],
            },
        ),
    ]
